# For use with pre-commit.
# See usage instructions at https://pre-commit.com

ci:
  skip: [pylama]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  # >>> pip-audit
  # https://pypi.org/project/pip-audit/#pre-commit-support
  # Tool for scanning Python environments for packages with known vulnerabilities
  - repo: https://github.com/pypa/pip-audit
    rev: v2.8.0
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt"]

  # >>> Pylama
  # https://github.com/klen/pylama/blob/develop/.pre-commit-hooks.yaml
  # Code audit tool for Python
  - repo: local
    hooks:
      - id: pylama
        name: pylama
        entry: pylama
        language: python
        types: [file, python]
        args: ["--linters", "mccabe,pyflakes,pylint"]
        additional_dependencies: []

  # >>> Ruff
  # https://github.com/astral-sh/ruff-pre-commit
  # An extremely fast Python linter and code formatter, written in Rust
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
      - id: ruff-format

  # >>> Codespell
  # https://github.com/codespell-project/codespell
  # Fixes common misspellings in text files
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  # >>> MyPy
  # https://github.com/pre-commit/mirrors-mypy
  # A static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          - --explicit-package-bases
          - --ignore-missing-imports
          - --install-types # See mirrors-mypy README.md
          - --non-interactive
        additional_dependencies: [types-requests]